// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package net.MissionEats.helloworld;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
